services:
  vuln-app:
    image: custom-vuln-app
    ports:
      - "8080:80"
    logging:
      driver: "splunk"
      options:
        splunk-token: "bb056fbe-a182-4ff6-8612-803df97d6d24"
        splunk-url: "https://172.16.25.2:8088"
        splunk-insecureskipverify: "true"
        splunk-sourcetype: "docker"
        splunk-index: "cyber_range"
        tag: "{{.ImageName}}/{{.Name}}"